[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
authors = [
  {name = ""},
  {email = ""},
]
license = {file = "LICENSE", name = "MIT"}
classifiers = []

[project.urls]
Homepage = ""
